LogLevel warn
PageLogFormat
MaxLogSize 0

Listen 0.0.0.0:631
Listen /run/cups/cups.sock

Browsing Off
DefaultAuthType Basic
WebInterface Yes
IdleExitTimeout 0

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>

<Location /admin/conf>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>

<Policy default>
  <Limit All>
    Order allow,deny
    Allow all
  </Limit>
</Policy>
